version: '3.4'

services : 

  backend : 
    container_name : backend
    build : 
      context : .\services\backend
      dockerfile : Dockerfile-dev
    volumes :  
      - '.\services\backend:/usr/src/app'
    ports : 
      - 5001:5000
    environment : 
        - FLASK_DEBUG=1
        - APP_SETTINGS=project.config.DevelopmentConfig
        - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
        - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
    depends_on : 
      - db
    links :
      - db
    
  db : 
    container_name : db
    build :
      context : .\services\backend\project\db
      dockerfile : Dockerfile
    ports : 
      - 5435:5432
    environment : 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
