"""empty message

Revision ID: 11bf40239ccf
Revises: 980f28d3b758
Create Date: 2018-06-15 10:50:50.214365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '11bf40239ccf'
down_revision = '980f28d3b758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fyle_tokens',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('tokens', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('username')
    )
    op.add_column('users', sa.Column('public_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'public_id')
    op.drop_table('fyle_tokens')
    # ### end Alembic commands ###
